### PR TITLE
feat(portal): image list filters, URL sync, sharing UX, and pagination-observer fixes   

### LINKED ISSUE #702: [Task](images):  iteration of images ui
**Task Description**

- [x] Content from Overview page is displayed on the parent node, not as a sibling of the parent
- [x] Tabs aren’t in history
- [x] Change revoke to reject in accepted images
- [x] change single button to kebap with single option
- [x] show confirm dialog for reject (both when triggered from list or from details view)
- [x] don’t save filters across tabs, only within the tab
- [x] Flickering loading indicator persists. But fix by changing to pagination instead of endless scroll
- [x] change order of suggested/accep

ted tabs

Custom Metadata:

- [x] Split Metadata in Details like in the modal
- [x] dont hard code it.  

where does the hardcoded list of “backend” metadata come from? ( System-Properties, Images properties  )
This must be configurable, not hardcoded -> Taimoor (eventually)

### PR DESCRIPTION
**Pull request by TilmanHaupt**
# Summary

Closes #702

This PR improves the Images section of the Compute service with a series of UX, correctness, and architecture fixes across the image list, image detail view, and metadata editor.

## Navigation & URL Sync

- SideNavBar section headers (Compute, Network) now navigate to their overview page on click instead of only toggling the section open
- Image detail tabs (Details / Sharing Details) are synced to the URL (`?tab=sharing`) and create browser history entries
- Image list tabs (All / Accepted / Suggested) are synced to the URL (`?memberStatus=accepted`) and create browser history entries — tab switches reset filters and are navigable with back/forward
- Tab order changed to: All → Accepted → Suggested

## Image Sharing / Member Status

- Renamed "Revoke" / "Revoke Access" → "Reject" throughout
- Accept and Reject actions moved from inline buttons into a PopupMenu 
- Both actions now show a confirmation modal before executing

## Filters

- Fixed multi-value status filter (`in:active,queued`) always returning empty — BFF was doing exact string match instead of array check
- Fixed filters not applying in Accepted / Suggested tabs — all filter params are now forwarded to `listSharedImagesByMemberStatus` which applies them BFF-side
- Fixed filter changes resetting the active tab back to "All Images"
- Fixed stale state in `useEffect` causing wrong `member_status` on tab switch

## Image Metadata Editor

- Metadata editor now shows all custom properties regardless of value type (non-strings are serialized); previously only string values were shown
- Excluded properties list moved out of hardcoded client code into `.env` as `IMAGE_METADATA_EXCLUDED_PROPERTIES` (comma-separated), served via a new tRPC query — see `.env.example`
- Edit button is hidden when the delete confirmation is active to prevent layout shifts

## Load More / Pagination

- Fixed Load More button flickering between states when filters change — hidden during full refetch so stale `nextMarker` doesn't flash
- IntersectionObserver now auto-fetches once per page when the sentinel scrolls into view, then resets after each successful load so subsequent pages also auto-load if the user hasn't scrolled away

## Test Plan

- Filter by multiple statuses (e.g., active + queued) in All Images tab → both show
- Filter by disk format, container format, protected in All Images tab → correctly filtered
- Switch to Accepted or Suggested tab, apply a status filter → results filtered within that tab, tab not reset
- Apply filters, then use browser back/forward → correct tab and filters restored
- Accept / Reject a shared image from the list → confirmation modal appears, action executes
- Open Edit Metadata modal → all custom properties visible including non-string values
- Scroll to bottom of a long image list → auto-loads next page once; further pages auto-load if still at bottom; Load More button available for manual trigger
- Confirm `.env.example` documents `IMAGE_METADATA_EXCLUDED_PROPERTIES`

# Checklist

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings or errors.

## Summary by CodeRabbit

* **New Features**
  * Member-status filter for shared images (All / Accepted / Pending) and URL-backed tab state for image details.
  * Endpoint to supply excluded image-metadata keys; example env file added.

* **Improvements**
  * Image metadata editor accepts broader value types and uses runtime reserved-key lists.
  * More comprehensive image filtering (status, format, protected) and reduced duplicate pagination requests.
  * Sidebar navigation labels and behavior updated.

* **Bug Fixes / UI**
  * Accept/Reject moved to confirm modals; “Revoke” relabeled “Reject”. Delete warnings use danger styling.

* **Tests**
  * Added tests for multi-value parsing and BFF filter behavior.

* **Localization**
  * Updated translation catalog (new/adjusted entries).

### CODE REVIEW

**Review by andypf — DISMISSED** [review]

**Review by andypf — DISMISSED** [review]

**Review by andypf — DISMISSED** [review]

File: apps/aurora-portal/src/client/routes/_auth/accounts/$accountId/projects/$projectId/compute/-components/Images/-components/ImageTableRow.tsx [hunk 1]
```diff
@@ -94,20 +93,8 @@ export function ImageTableRow({
...
-    }
-  }, [confirmRevoke])
-  useEffect(() => {
-    if (confirmReject) {
-      const timer = setTimeout(() => setConfirmReject(false), 3000)
-      return () => clearTimeout(timer)
-    }
-  }, [confirmReject])
+  const [acceptModalOpen, setAcceptModalOpen] = useState(false)
+  const [rejectModalOpen, setRejectModalOpen] = useState(false)
```
Comment (vlad-schur-external-sap) [inline apps/aurora-portal/src/client/routes/_auth/accounts/$accountId/projects/$projectId/compute/-components/Images/-components/ImageTableRow.tsx]: LGTM. Just replace these 2 useState with `useModal` hook ` from "@/client/utils/useModal"`

Comment (TilmanHaupt) [reply apps/aurora-portal/src/client/routes/_auth/accounts/$accountId/projects/$projectId/compute/-components/Images/-components/ImageTableRow.tsx]: You can again :)

**Review by KirylSAP — DISMISSED** [review]

**Review by vlad-schur-external-sap — APPROVED** [review]

**Review by andypf — APPROVED** [review]
