### PR TITLE
fix(dashboard): seperate router to ensure there is no circular dependency

### LINKED ISSUE #202: [Bug](context): Auth login page is out of sync
**Description**

Unexpected logout/redirection to login page occurs even when the session is still valid on the server.

**Steps to Reproduce**

1. Log in to the app.
2. Navigate and work normally.
3. Leave the page (e.g., switch tab or route), then return.

**Expected Behavior**

User should remain logged in and not be redirected to the login page if the session is still valid.

**Screenshots**

**Environment**

- OS: macOS  
- Browser: Chrome  
- Version: 123

**Additional Context**

Likely caused by auth logic in route hooks or invalidation triggers. We're using TanStack Router. Console shows errors related to the hook. Needs investigation around auth guards and redirect logic.

### PR DESCRIPTION
**Pull request by TilmanHaupt**
# Summary

Warning "useRouter must be used inside a <RouterProvider> component!" solved by resolving circular dependencies.
Automatic logins through correct reconnects and checks inside of __auth

# Changes Made

New router File
New reconnects

# Related Issues

closes #202 

# Testing Instructions

1. `pnpm i`
2. `pnpm run test`

# Checklist

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings or errors.

### CODE REVIEW

File: apps/aurora-portal/src/client/store/AuthProvider.tsx [hunk 1]
```diff
@@ -18,8 +19,6 @@ export function AuthProvider({ children }: { children: React.ReactNode }) {
   const [expiresAt, setExpiresAt] = React.useState<Date | undefined>(undefined)
   const logoutTimerRef = useRef<NodeJS.Timeout | null>(null)
 
-  const router = useRouter()
```
Comment (barsukov) [inline apps/aurora-portal/src/client/store/AuthProvider.tsx:21]: the only little problem that I see now that you need to explicitly mock ../router for writing a tests on this provider but maybe it is the way to go, WDYT? @andypf

Comment (TilmanHaupt) [reply apps/aurora-portal/src/client/store/AuthProvider.tsx:21]: Found this solution here: https://github.com/TanStack/router/discussions/2978

File: apps/aurora-portal/src/client/routes/_auth/accounts/index.tsx [hunk 2]
```diff
@@ -2,8 +2,16 @@ import { createFileRoute, redirect } from "@tanstack/react-router"
 
 export const Route = createFileRoute("/_auth/accounts/")({
   component: RouteComponent,
```
Comment (andypf) [inline apps/aurora-portal/src/client/routes/_auth/accounts/index.tsx:4]: If this component never rendered, can we just remove it

Comment (TilmanHaupt) [reply apps/aurora-portal/src/client/routes/_auth/accounts/index.tsx]: very good idea!!!

**Review by andypf — APPROVED** [review]
Super
